Include py.typed in package
Otherwise mypy complains about
  error: Skipping analyzing "imageio.v3":
    module is installed, but missing library stubs or py.typed marker

when importing
  import imageio.v3 as iio